### ISSUE TITLE
test whether two slices have equal content

### ISSUE THREAD

**Issue by LarsFronius** [stretchr/testify#275] opened 2016-02-16 14:03 UTC
I wonder if this inside the scope of testify.
Basically I have two slices of a certain type, which can be of random order and I want to be able to compare, that any of the data of one slice appears on the other slice as well.
A reflect.deepequal does not get the job done, neither does assert.Equal, so is this something to consider as a feature for testify?
e.g.

```go
type foobar struct {
    Key string,
    Value string
}

var foobar_slice []*foobar
foobar_slice = append(settings_slice, &pushservice.Setting{Key: "foobar", Value: "barbaz"})
foobar_slice = append(settings_slice, &pushservice.Setting{Key: "bazfoo", Value: "foobaz"})

var barbaz_slice []*foobar
barbaz_slice = append(settings_slice, &pushservice.Setting{Key: "bazfoo", Value: "foobaz"})
barbaz_slice = append(settings_slice, &pushservice.Setting{Key: "foobar", Value: "barbaz"})

assert.EqualSlice(t, foobar_slice, barbaz_slice)
```

**Comment by ernesto-jimenez** [comment] 2016-02-16 17:07
Hi @LarsFronius, `assert.EqualSlice` is a bit misleading, since two slices with different order are different.

Before finding the right name for the method there would need to be some clarification on the behaviour:

 - Is it just confirming that all events from the `actual` slice are contained in the `expected` slice and vice versa?
 - What would happen with duplicated elements? e.g: `actual` and `equal` have the same elements but `actual` has one that is duplicated. Would the assertion fail?

Sounds like you might be thinking about `assert.ContainsSameElements`.

**Comment by ernesto-jimenez** [comment] 2016-09-24 20:39
I think this would be out of scope.

It's probably better for the developer to sort both arrays and then call `assert.Equal`

**Closed by ernesto-jimenez** 2016-09-24 20:39 UTC

**Comment by narg95** [comment] 2017-02-17 15:38
`assert.ContainsSameElements` would be great! 
In my case, I have a integration test and I get some data from the database that it may come in different order every time I run it, and I just want to assert that the elements that I expect are there. This function will make my assertion easier. 
I know it is closed but +1.

**Comment by DennisMao** [comment] 2019-04-08 13:05
Now it's  the  `assert.ElementsMatch(t, expectedSlice, actualSlice)`

**Comment by sarathsp06** [comment] 2019-05-23 06:56
@DennisMao is there a way to do the same in `Mock.On`

**Comment by ilovejs** [comment] 2023-08-15 02:54
...
```
Expected :[]string{"g1", "f3", "ze"}
Actual   :[]string{"f3", "g1", "ze"}
```

**Comment by fangpinsern** [comment] 2023-09-05 07:28
@ilovejs if this is an issue with `assert.ElementsMatch`, i could not reproduce it
