### ISSUE TITLE
go-difflib is no longer maintained

### ISSUE THREAD

**Issue by mat285** [stretchr/testify#1187] opened 2022-05-12 18:00 UTC
It appears that https://github.com/pmezard/go-difflib is no longer maintained, but is still a dependency of this project. Are there any plans to remove it/fork and maintain a copy of it?

**Comment by dolmen** [comment] 2023-07-25 04:42
Duplicate of #1327.

**Comment by dolmen** [comment] 2023-07-25 04:44
What are the issues with go-difflib that require fixing?

**Comment by brackendawson** [comment] 2024-10-08 13:18
Duplicate of #1159

**Closed by brackendawson** 2024-10-08 13:18 UTC
Labels: rejected/duplicate, dependencies
