### ISSUE TITLE
Equal integers not registering as equal

### ISSUE THREAD

**Issue by cdipaolo** [stretchr/testify#157] opened 2015-04-29 00:42 UTC
I'm having problems, only when running in Wercker builds (local machine works fine,) with having integers that are obviously equal registering as unequal. See below. Is this due to a difference in 'reflect.DeepEquals()' implementations when compiled to different operating systems? 

```bash
--- FAIL: TestShouldFail2 (0.00s)
	Location:	x_test.go:311
	Error:		Not equal: 5 (expected)
			        != 5 (actual)
	Messages:	x should be 5
		
	Location:	x_test.go:312
	Error:		Not equal: 10 (expected)
			        != 10 (actual)
	Messages:	x should be 10
		
	Location:	x_test.go:313
	Error:		Not equal: 0 (expected)
			        != 0 (actual)
	Messages:	x should be 0
		
	Location:	x_test.go:314
	Error:		Not equal: 0 (expected)
			        != 0 (actual)
	Messages:	x should be 0
```

Not causing any problems currently but is a little annoying. Thanks in advance.

**Comment by DAddYE** [comment] 2015-04-29 05:19
Can you try with assert.EqualValues ?

Sent from my iPhone

On Apr 28, 2015, at 5:42 PM, Conner DiPaolo <notifications@github.com>
wrote:

I'm having problems, only when running in Wercker builds (local machine
works fine,) with having integers that are obviously equal registering as
unequal. See below. Is this due to a difference in 'reflect.DeepEquals()'
implementations when compiled to different operating systems?

--- FAIL: TestShouldFail2 (0.00s)
    Location:   x.go:311
    Error:      Not equal: 5 (expected)
                    != 5 (actual)
    Messages:   x should be 5

    Location:   x_test.go:312
    Error:      Not equal: 10 (expected)
                    != 10 (actual)
    Messages:   x should be 10

    Location:   x.go:313
    Error:      Not equal: 0 (expected)
                    != 0 (actual)
    Messages:   x should be 0

    Location:   x.go:314
    Error:      Not equal: 0 (expected)
                    != 0 (actual)
    Messages:   x should be 0

Not causing any problems currently but is a little annoying. Thanks in
advance.

—
Reply to this email directly or view it on GitHub
<https://github.com/stretchr/testify/issues/157>.

**Comment by pkieltyka** [comment] 2015-04-30 14:03
I'm experiencing this as well.

@DAddYE assert.EqualValues is still pretty generic, not much different then .Equal()

..the way I've been solving this is using `assert.True(9 == x)`

**Comment by pkieltyka** [comment] 2015-04-30 14:06
@DAddYE ah, I didn't realize EqualValues already existed in the library. I've tried it and confirmed that EqualValues solves this issue.

**Comment by nathany** [comment] 2015-05-26 21:53
I ran into an issue where this code would fail on Travis CI (sudo: false containers) but pass locally (64-bit OS X). Go 1.4.2 in both cases.

```go
assert.Equal(t, 7, r.ContentLength)
```

It's something due to the types. r.ContentLength is an int64 (see [http.Request](http://golang.org/pkg/net/http/#Request)). If I convert the type in advance it works.

```go
assert.Equal(t, int64(7), r.ContentLength)
```

**Comment by cdipaolo** [comment] 2015-05-26 22:11
Yeah I tried using assert.EqualValues and it worked. I'd thing that type
casting explicitly would work and it has for some of my tests (usually with
floats) but I hadn't tried casting integers. Try EqualValues for a quick
fix or if you don't really care what the explicit type is (or know that it
will definitely be an int64 for example, like when calling a struct value.

**Comment by nathany** [comment] 2015-05-26 22:20
Thanks, EqualValues works too.

```
assert.EqualValues(t, 7, r.ContentLength)
```

**Comment by ernesto-jimenez** [comment] 2015-11-02 01:11
Closing this issue in favour of a new one to improve the error messages: https://github.com/stretchr/testify/issues/231

**Closed by ernesto-jimenez** 2015-11-02 01:11 UTC
