### ISSUE TITLE
"MISSING" appearing in binary diffs

### ISSUE THREAD

**Issue by Alexendoo** [stretchr/testify#544] opened 2018-01-06 15:30 UTC
Binary diffs seem to include some odd output, it's reproducible wherever the byte 0x25 appears:

```go
func TestTestify(t *testing.T) {
	assert.Equal(t, []byte{0x25}, []byte{0x26})
}
```

with the output:
```
--- FAIL: TestTestify (0.00s)
	assertions.go:247: 
                          
	Error Trace:	main_test.go:7
		
	Error:      	Not equal: 
		
	            	expected: []byte{0x25}
		
	            	actual  : []byte{0x26}
		
	            	
		
	            	Diff:
		
	            	--- Expected
		
	            	+++ Actual
		
	            	@@ -1,3 +1,3 @@
		
	            	 ([]uint8) (len=1) {
		
	            	- 00000000  25                                                |%!|(MISSING)
		
	            	+ 00000000  26                                                |&|
		
	            	 }

```

**Comment by mvdkleijn** [comment] 2020-04-07 22:19
Cannot reproduce this with 1.5.1 so closing

**Closed by mvdkleijn** 2020-04-07 22:19 UTC
