### ISSUE TITLE
compare two function object

### ISSUE THREAD

**Issue by xuruiray** [stretchr/testify#565] opened 2018-02-27 10:34 UTC
```
assert.EqualValuesf(t, v.want, result, "name: %v", v.name)

Error:      	Not equal: 
expected: (http.HandlerFunc)(0x126f610)
actual  : (http.HandlerFunc)(0x126f610)

assert.Equal(t, v.want, result, "name: %v", v.name)

Error:      	Invalid operation: (http.HandlerFunc)(0x126fcd0) == (http.HandlerFunc)(0x126fcd0) (cannot take func type as argument)
```
package assert can't  compare two function object，can you provide related functions ？😊

**Comment by ernesto-jimenez** [comment] 2018-03-03 14:46
@xuruiray this is a duplicate of https://github.com/stretchr/testify/issues/182

The short answer: it is currently impossible to reliably compare two functions using the `reflect` package.

> If v's Kind is Func, the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely. The only guarantee is that the result is zero if and only if v is a nil func Value.

**Closed by ernesto-jimenez** 2018-03-03 14:46 UTC
