### ISSUE TITLE
assert Equal with string that contain "%" attempts to resolve it

### ISSUE THREAD

**Issue by ggeorgiev** [stretchr/testify#416] opened 2017-03-28 14:46 UTC
assert Equal with a string that contains "%" attempts to resolve it

For example: 	`assert.Equal(t, "something %d", "something else %s")` will result in:

	Error:      	Not equal: 
	            	expected: "something %!d(MISSING)"
	            	received: "something else %!s(MISSING)"

**Comment by HaraldNordgren** [comment] 2018-09-15 11:30
@ggeorgiev Which version of testify are you using? I cannot reproduce this even on v1.0 which was released in 2015.

**Comment by dolmen** [comment] 2023-07-06 19:27
Here is the full runnable test case on go.dev/play: https://go.dev/play/p/SQgS39IqR-d

This doesn't happen on testify 1.8.4, so I'm closing as invalid.

**Closed by dolmen** 2023-07-06 19:27 UTC
Labels: pkg-assert, invalid
