### ISSUE TITLE
Question: go get -t ./... does not pull github.com/stretchr/objx the first time run on OSX with go1.5

### ISSUE THREAD

**Issue by jshort** [stretchr/testify#214] opened 2015-09-14 18:20 UTC
I recently converted my unit tests to use testify/assert and my travis ci builds work fine:

$ go get -t -v ./...
github.com/droundy/goopt (download)
github.com/stretchr/testify (download)
github.com/droundy/goopt
github.com/jshort/gocurl/cliutils
github.com/jshort/gocurl/httputils
github.com/jshort/gocurl

But on my OSX 10.9 machine, I have to run it twice:

(11:12) laptop gocurl > rm -rf src/github.com/stretchr/
(11:18) laptop gocurl > rm -rf pkg/darwin_amd64/github.com/stretchr/
(11:18) laptop gocurl > go get -t -v ./...
github.com/stretchr/testify (download)
src/github.com/stretchr/testify/mock/mock.go:11:2: cannot find package "github.com/stretchr/objx" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/stretchr/objx (from $GOROOT)
	/Users/me/gitworkspaces/gocurl/src/github.com/stretchr/objx (from $GOPATH)
(11:18) laptop gocurl > go get -t -v ./...
github.com/stretchr/objx (download)
github.com/stretchr/objx
github.com/stretchr/testify/assert
github.com/stretchr/testify/require
github.com/stretchr/testify/suite
github.com/stretchr/testify/mock
github.com/stretchr/testify/http
github.com/stretchr/testify
(11:19) laptop gocurl >

**Comment by CMogilko** [comment] 2015-09-16 10:27
Same problem on Ubuntu with go 1.5.

**Comment by ernesto-jimenez** [comment] 2015-11-02 00:01
@jshort @CMogilko sorry for the late reply, I'm super busy and just catching-up with the PRs and issues.

Is this still an issue? have you been able to do any debugging since then?

Thanks!
Ernesto

**Comment by CMogilko** [comment] 2015-11-02 08:37
@ernesto-jimenez 
I couldn't reproduce it with go 1.5.1.

**Comment by ernesto-jimenez** [comment] 2016-01-10 11:38
I'm closing this since we've not been able to reproduce it.

If somebody else has the issue please comment with some steps to reproduce the problem and I'll reopen the issue.

Thanks!

**Closed by ernesto-jimenez** 2016-01-10 11:38 UTC

**Comment by iampeterbanjo** [comment] 2018-10-12 06:06
I seem to have this problem working on adding some unit tests. I have run `go get -u github.com/stretchr/testify` and I'm getting the error message

```
cannot find package "github.com/stretchr/testify/mock" in any of:
    /home/iampeterbanjo/golang/src/github.com/iampeterbanjo/riffraff/vendor/github.com/stretchr/testify/mock (vendor tree)
    /home/iampeterbanjo/.asdf/installs/golang/1.11.1/go/src/github.com/stretchr/testify/mock (from $GOROOT)
    /home/iampeterbanjo/golang/src/github.com/stretchr/testify/mock (from $GOPATH)
```

go env  >>
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/iampeterbanjo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/iampeterbanjo/golang"
GOPROXY=""
GORACE=""
GOROOT="/home/iampeterbanjo/.asdf/installs/golang/1.11.1/go"
GOTMPDIR=""
GOTOOLDIR="/home/iampeterbanjo/.asdf/installs/golang/1.11.1/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/iampeterbanjo/golang/src/github.com/iampeterbanjo/riffraff/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build637701243=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by iampeterbanjo** [comment] 2018-10-12 06:08
I'm working on this repo [github.com/iampeterbanjo/riffraff] so could you please clone it and try and add testify as a dependency?

**Comment by iampeterbanjo** [comment] 2018-10-12 06:12
The first time I ran it I did get this output 

```
go: finding github.com/stretchr/testify/mock latest
go: downloading github.com/stretchr/testify v1.2.2
go: downloading github.com/davecgh/go-spew v1.1.1
go: finding github.com/stretchr/objx v0.1.1
go: downloading github.com/stretchr/objx v0.1.1
```

but I can't find the package anywhere on my machine and re-running `go get github.com/stretchr/testify` isn't doing anything.

**Comment by CMogilko** [comment] 2018-10-12 20:35
@iampeterbanjo it seems that you misunderstood go1.11 modules and old-style GOPATH. With go1.11 modules turned on GOPATH doesn't used anymore.

**Comment by iampeterbanjo** [comment] 2018-10-12 22:14
@CMogilko thanks. I had my project in $GOPATH and moving it out of there seems to have resolved the issue.
