### ISSUE TITLE
Formatting unsigned integers (in formatUnequalValue or truncatingFormat) with %v instead of %#v

### ISSUE THREAD

**Issue by tjanez** [stretchr/testify#1116] opened 2021-09-15 12:00 UTC
[Example](https://play.golang.org/p/cdSZMaXmvLR):

```go
package main

import (
	"github.com/stretchr/testify/require"
	"testing"
)

func TestUnsignedInt(t *testing.T) {

	var a uint64 = 1234567
	var b uint64 = 98765523

	require.Equal(t, a, b, "The two numbers should be the same.")

}
```

This results in hex-formatted integers:
```
=== RUN   TestUnsignedInt
    prog.go:13: 
        	Error Trace:	prog.go:13
        	Error:      	Not equal: 
        	            	expected: 0x12d687
        	            	actual  : 0x5e30ad3
        	Test:       	TestUnsignedInt
        	Messages:   	The two numbers should be the same.
--- FAIL: TestUnsignedInt (0.00s)
FAIL
```

Replacing `%#v` with `%v` in `truncatingFormat()`:
https://github.com/stretchr/testify/blob/c26b7f39f88ecc339b622fcbe6531ac5fdccd799/assert/assertions.go#L447

would result in decimal-formatted integers:
```
=== RUN   TestUnsignedInt
    prog.go:13: 
        	Error Trace:	prog.go:13
        	Error:      	Not equal: 
        	            	expected: 1234567
        	            	actual  : 98765523
        	Test:       	TestUnsignedInt
        	Messages:   	The two numbers should be the same.
--- FAIL: TestUnsignedInt (0.00s)
FAIL
```

---

There was a similar issue for `time.Duration` type (#626) which was solved with special casing in `formatUnequalValue()`:
https://github.com/stretchr/testify/blob/c26b7f39f88ecc339b622fcbe6531ac5fdccd799/assert/assertions.go#L435-L438

---

A similar broader thing is tracked in #390.

**Comment by mrdengbo** [comment] 2021-12-21 05:56
Replacing %#v with %T(%v) in truncatingFormat(), The formatted output parameters are as follows:
![image](https://user-images.githubusercontent.com/37774387/146879007-2ad763f2-c7b7-48a6-b044-9d66e102ce9a.png)

**Comment by nomaed** [comment] 2024-09-29 15:22
Bumping this. It's been so long and seeing such errors on comparison of number is so weird:

```
        	Error:      	Not equal: 
        	            	expected: 0xa
        	            	actual  : 0x1
```

**Comment by brackendawson** [comment] 2024-10-06 15:11
I'd support a PR which formats all things which are convertible to the numeric and complex types with `%T(%v)`.

**Comment by brackendawson** [comment] 2024-10-07 12:29
Duplicate of 400, which already has a PR.

**Closed by brackendawson** 2024-10-07 12:29 UTC
