### ISSUE TITLE
deps: go-difflib is EOL

### ISSUE THREAD

**Issue by satish-suradkar** [stretchr/testify#1327] opened 2023-01-18 09:35 UTC
`github.com/pmezard/go-difflib v1.0.0` is an EOL.

Any plan to use an alternative for this?

**Comment by brackendawson** [comment] 2023-01-18 10:20
Probably something else that go-cmp would be suitable for. Ref #535 

For this issue it's not a breaking change.

**Comment by dolmen** [comment] 2023-07-25 02:41
A project not maintained doesn't mean the code doesn't work as is.

Do you see any issue that are relevant to testify?

**Comment by brackendawson** [comment] 2024-10-08 13:18
Duplicate of #1159

**Closed by brackendawson** 2024-10-08 13:18 UTC
Labels: help wanted, dependencies, internal/refactor
