### ISSUE TITLE
Give permissions on project to other active developers

### ISSUE THREAD

**Issue by dennypenta** [stretchr/testify#709] opened 2018-12-26 12:41 UTC
If you have no time to maintain the project, what about to give active develops permission on the project?
You can bind a lint to an active fork in README.
I waited for an answer to my previous issue 2 month, I find it enough long time. 
I'm seeing that 2 pull requests important for me are stacked for several months, one about naming generated mocks and one I wanna make about comparing empty slices in structs and show a shorter diff for large structs.

**Comment by letientai299** [comment] 2019-01-03 14:05
As I'm using it for my work, I would love to be a maintainer for this project. 

cc @georgelesica-wf

**Comment by georgelesica-wf** [comment] 2019-01-03 16:07
@dennypenta could you link to those pull requests here? I took over as a maintainer a couple months back, but I haven't had time to triage existing PRs and issues, I've just been reviewing and merging changes as they are brought to my attention.

@letientai299 let me think on that. I am in favor of increasing the number of maintainers, but I need to put in the time to make sure we can handle that effectively (we're probably going to need some community-building).

**Comment by JordanP** [comment] 2019-01-08 18:01
Whatever is decided, please do it very carefully. A lot of people are depending on this package :)

**Comment by letientai299** [comment] 2019-05-23 06:20
@georgelesica-wf do you have any decision about adding me as a new maintainer yet? There's a lot of incoming issues and PR that I can help.

**Comment by dolmen** [comment] 2023-07-07 08:41
Duplicate of #152.

**Closed by dolmen** 2023-07-07 08:41 UTC
Labels: rejected/duplicate, community
