### ISSUE TITLE
assert.Equal with pointers prints address instead of value on failure

### ISSUE THREAD

**Issue by ashmrtn** [stretchr/testify#1273] opened 2022-09-28 18:12 UTC
testify version: v1.8.0

Comparing pointers to values with `Equal` prints the address of the value if the comparison fails instead of the value. This can be confusing to users as it makes it seem like the addresses are being compared instead of the values.

I have verified this behavior for both `*string` and `*int` types. Comparisons between `nil` and some non-nil pointer also prints the address of the non-nil value

Example:
```go
func EqualOutputString(t *testing.T) {
  e := "hello"
  g := "hola"
  ep := &e
  gp := &g

  assert.Equal(t, ep, gp)
  assert.Equal(t, ep, nil)
}

func EqualOutputInt(t *testing.T) {
  e := 7
  g := 42
  ep := &e
  gp := &g

  assert.Equal(t, ep, gp)
}
```

test output:
```
=== RUN   TestEqualOutputString
    equal_output_test.go:15: 
                Error Trace:    /go/src/output_test/equal_output_test.go:15
                Error:          Not equal: 
                                expected: (*string)(0x4000573530)
                                actual  : (*string)(0x4000573540)
                            
                                Diff:
                Test:           TestEqualOutputString
    equal_output_test.go:16: 
                Error Trace:    /go/src/output_test/equal_output_test.go:16
                Error:          Not equal: 
                                expected: *string((*string)(0x400006aec0))
                                actual  : <nil>(<nil>)
                Test:           TestEqualOutputString
--- FAIL: TestEqualOutputString (0.00s)
=== RUN   TestEqualOutputInt
    equal_output_test.go:24: 
                Error Trace:    /go/src/output_test/equal_output_test.go:24
                Error:          Not equal: 
                                expected: (*int)(0x4000546b10)
                                actual  : (*int)(0x4000546b18)
                Test:           TestEqualOutputInt
--- FAIL: TestEqualOutputInt (0.00s)
```

**Comment by brackendawson** [comment] 2022-09-28 20:51
This is #1118

**Comment by ashmrtn** [comment] 2022-09-28 20:59
ah, my apologies, I did some digging for an existing issue but must not have searched for the right words or skimmed over the title as I happened to be thinking of a different thing

**Comment by dolmen** [comment] 2023-07-12 14:33
Duplicate of #1118

**Closed by dolmen** 2023-07-12 14:33 UTC
Labels: enhancement, pkg-assert, rejected/invalid
