### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by philtay** [stretchr/testify#303] opened 2016-04-25 00:26 UTC
The following test fails. Is it a bug or do I miss something?

```go
import (
   "strings"
   "testing"
   "text/template"

   "github.com/stretchr/testify/assert"
)

func TestFuncMap(t *testing.T) {
	fm1 := template.FuncMap{
		"title": strings.Title,
	}

	fm2 := template.FuncMap{
		"title": strings.Title,
	}

	assert.Equal(t, fm1, fm2)
}
```

**Comment by ernesto-jimenez** [comment] 2016-04-25 07:53
Functions are not comparable in Go.






On Sun, Apr 24, 2016 at 5:26 PM -0700, "philtay" <notifications@github.com> wrote:












The following test fails. Is it a bug or do I miss something?

import (
   "strings"
   "testing"
   "text/template"

   "github.com/stretchr/testify/assert"
)

func TestFuncMap(t *testing.T) {
    fm1 := template.FuncMap{
        "title": strings.Title,
    }

    fm2 := template.FuncMap{
        "title": strings.Title,
    }

    assert.Equal(t, fm1, fm2)
}

**Comment by philtay** [comment] 2016-04-25 16:59
Most probably a workaround can be implemented. Have a look here: https://github.com/golang/go/issues/8554

**Comment by ernesto-jimenez** [comment] 2016-04-26 14:39
@philtay, this is a duplicate of #159 and #182.

You can find the explanation on the current Go limitations that prevent us from doing function comparison in those issues.

If/When Go addresses this, we'll address it too.

**Closed by ernesto-jimenez** 2016-04-26 14:39 UTC
