### ISSUE TITLE
unnecessary/incorrect log call in AssertExpectations

### ISSUE THREAD

**Issue by win-arturo** [stretchr/testify#1543] opened 2024-02-20 18:11 UTC
## Description
When running tests and making the AssertExpectations call, log of any successful expected call is unnecessarily output.

## Step To Reproduce
m := &mock.Mock{}
m.On("someCall")
m.AssertExpectations(t)
## Expected behaviour
If the call is made, as expected, no output should be generated.  This is in keeping with test first philosophy that a test that requires a human to read its output is not a good test.
## Actual behaviour
  some_test.go:107: PASS:	Get(*mock.IsTypeArgument,string,string)

personally, I think that the log statement is in the wrong place:

	expectedCalls := m.expectedCalls()
	for _, expectedCall := range expectedCalls {
		satisfied, reason := m.checkExpectation(expectedCall)
		if !satisfied {
			failedExpectations++
		}
		t.Logf(reason) // <-- wrong place
	}

	expectedCalls := m.expectedCalls()
	for _, expectedCall := range expectedCalls {
		satisfied, reason := m.checkExpectation(expectedCall)
		if !satisfied {
			failedExpectations++
		        t.Logf(reason) // <-- correct place
		}
	}

**Comment by st3penta** [comment] 2024-02-20 21:34
I can do this one, if you agree

**Comment by brackendawson** [comment] 2024-02-20 23:14
That's because the playground will import the latest release of testify (v1.8.4) and this was fixed after that in #1360, you must have later version locally.

I intend to tag v1.8.5 quite soon, once all the already approved PRs are resolved. If that's not soon enough, you can `go get github.com/stretchr/testify@master`.

Closing as duplicate of #1358, thank you for reporting.

**Closed by brackendawson** 2024-02-20 23:14 UTC
Labels: bug, good first issue
