### ISSUE TITLE
Mocks: Question: mock.MatchedBy two times called when the function targeted is call 1 time

### ISSUE THREAD

**Issue by alexisvisco** [stretchr/testify#1415] opened 2023-07-11 12:29 UTC
file.go: 
```
package test_gomock

//go:generate mockery --name=Name --output=mocks --outpkg=mocks --case=underscore --with-expecter=true
type Name interface {
	Call(str string)
}

func Test(n Name) {
	n.Call("test")
}

```

test.go 
```
package test_gomock

import (
	"fmt"
	"github.com/stretchr/testify/mock"
	"test-gomock/mocks"
	"testing"
)

func TestFile(t *testing.T) {
	name := mocks.NewName(t)
 
        // note: using the expecter codegen change nothing
	name.On("Call", mock.MatchedBy(func(str string) bool {
		fmt.Println("handler 1", str)
		return str == "test"
	}))

	Test(name)
}
```

Output : 

```
=== RUN   TestFile
handler 1 test
handler 1 test
    name.go:62: PASS:	Call(mock.argumentMatcher)
--- PASS: TestFile (0.00s)
PASS

```

Someone could explain why the MatchedBy function handler is called two times ?

**Comment by brackendawson** [comment] 2023-07-11 14:14
I think this is a duplicate of #1364 

As to your question of why; I can't recreate that behaviour with the code you've given, can you provide a full compilable example? One reason it may be called again is from AssertExepectations.

**Comment by brackendawson** [comment] 2024-02-17 17:57
The OP's example doesn't compile but I'm confident this is another #1364

**Closed by brackendawson** 2024-02-17 17:57 UTC
Labels: input needed, pkg-mock, question, mockery
