### ISSUE TITLE
On same mock,next method mocking will override previous methods mocking if  methods have similar literals

### ISSUE THREAD

**Issue by AlexLuya** [stretchr/testify#166] opened 2015-05-18 10:59 UTC
Hello,
    I have a mock like this:

````go
type SameType struct{}
type DiffType struct{}

type ServiceMock struct{
	mock.Mock
}

func (s *ServiceMock) RetrieveHomepageOnlyData(arg0 *DiffType, arg1 * SameType) error {
	args := s.Mock.Called(arg0, arg1)


	if args.Get(0) != nil {
		return args.Error(0)
	}

	return nil
}

func (s *ServiceMock) ToCache(arg0 string, arg1 *SameType) error {
	args := s.Mock.Called(arg0, arg1)

	if args.Get(0) != nil {
		return args.Error(0)
	}

	return nil
}
````
As you noticed,the second args of two methods have same type,and if I mock these two methods in same test with same second arg value like this:

````go
initDataService:=new(ServiceMock)
arg0=new(DiffType)
sameSecondValue=new(SameType)

func testMethod(){
             //given
             initDataService.On("RetrieveHomepageOnlyData", arg0, sameSecondValue).Return(nil)
             initDataService.On("ToCache","user-001", sameSecondValue).Return(nil)

             //when
             //.....

            //then
            //...
}
````

then only second mocking will take effect,and if running this test,I will get an error like this:

````go
    RetrieveHomepageOnlyData(*DifferentType,*SameType)
                0: &{[] [] [] []  user-001 [] 0 [] [] [{   0  false 0 false message-002        }] [] [remind-001] [remind-001] [] session-newClient [] [{false 0    tweet-001}]  <nil>}
                1: &{ [] [] [] []  0 [] [] [] [] [] session-newClient [] 0xc20812c990 <nil>}
    
    The closest call I have is: 
    
    RetrieveHomepageOnlyData(string,*SameType)
                0: user-001
                1: &{SIGNIN [] [] [] []  0 [] [] [] [] [] session-newClient [] 0xc20812c7e0 <nil>}
````

Obviously,the second mocking(on method "ToCache()") is used to match first mocking(on method RetrieveHomepageOnlyData()).

**Comment by ernesto-jimenez** [comment] 2015-11-02 01:02
@AlexLuya I tried the code that you provided and everything works as expected. I'm guessing the problem is with how you are actually sing the library since that error correspond to other code rather than the one you provided.

I'm closing the issue, but if you are still having issues please post a complete example and I'll be happy to help.

**Closed by ernesto-jimenez** 2015-11-02 01:02 UTC
