### ISSUE TITLE
SetupTest does not run on subtests

### ISSUE THREAD

**Issue by ahoulgrave** [stretchr/testify#832] opened 2019-10-25 09:43 UTC
Here you can see test failing
https://play.golang.org/p/R3m0s_PxwGG

If we call `SetupTest()` manually inside the subtest works correctly: https://play.golang.org/p/XpsmRqH2F4t

Is this intended behaviour?

**Comment by NefixEstrada** [comment] 2020-03-18 08:36
What's the state of this? I'd really use a hook like `SetupSubTest` or something like this. I use subtests not just for table testing but for documenting each scenario of the function that I'm testing, and thus I end up executing SetupTest on each subtest. Maybe we could implement it in a PR or something?

**Comment by gsagrawal** [comment] 2022-06-03 04:44
duplicate of https://github.com/stretchr/testify/issues/1031

**Closed** 2022-11-02 11:47 UTC
