### ISSUE TITLE
the binary dump has a strange word '(MISSING)' for some bytes

### ISSUE THREAD

**Issue by ggeorgiev** [stretchr/testify#334] opened 2016-07-29 18:34 UTC
When I use the require.Equal for binary data from time to time I in the dump: (MISSING) 

- 00000000  51 7a 21 15 85 4a 39 1b  25 a8 2c e1 e8 01 1e 8a  |Qz!..J9.%!,(MISSING).....|
- 00000010  f5 de 97 ab 9e 22 29 15  e5 38 39 73 ea 39 f8 09  |.....")..89s.9..|

**Comment by billf** [comment] 2016-08-09 22:09
you're not passing the same number of arguments as you have formatting strings, check out the "format errors" section of  https://golang.org/pkg/fmt/

> Too few arguments: `%!verb(MISSING)`
	`Printf("hi%d")`:            `hi %!d(MISSING)`

**Comment by ernesto-jimenez** [comment] 2016-09-24 18:47
@ggeorgiev can you share an example of input that would make this happen?

**Comment by ernesto-jimenez** [comment] 2016-09-24 19:09
I just saw this is a duplicate of #325

**Closed by ernesto-jimenez** 2016-09-24 19:09 UTC
Labels: input needed
