### ISSUE TITLE
Feature request: ErrorContains

### ISSUE THREAD

**Issue by markuswustenberg** [stretchr/testify#497] opened 2017-09-04 13:12 UTC
I'm using this pattern a lot:

```
require.Error(t, err)
require.Contains(t, err.Error(), "some part of the error string")
```

Although `require.ErrorEqual` is pretty useful at times, often I only want to match on part of the error message (maybe because some of it is dynamic for each test run or in different test environments).

Proposal: Add `require.ErrorContains()`

**Comment by markuswustenberg** [comment] 2017-09-04 13:13
I'd be happy to implement this myself if it sounds useful.

**Comment by dnephin** [comment] 2017-11-16 18:08
I opened #486 a little while ago, no response about it yet.

**Comment by ernesto-jimenez** [comment] 2017-12-30 16:05
This has been proposed a couple of times.

My main concern is that such an assertion is encouraging anti-patterns.

Too many new go developers rely on parsing error messages to implement their programs rather than using types.

If this kind of situation is uncommon, is it worth adding a that will nudge people into doing the wrong thing?

If we were to do a new major version breaking backwards compatibility, I would consider removing `EqualError` too for the same reason.

**Comment by dnephin** [comment] 2017-12-30 22:02
> Too many new go developers rely on parsing error messages to implement their programs rather than using types.

I certainly agree that parsing strings from an error message is not a good pattern for handling errors.

However, that still leaves the question of how should tests check for errors?

I would argue that the current `assert.Equal()` is even worse. It does nothing to encourage types, and can be very misleading:

```go
// Could be any error! The test case may not even be reaching the condition
// I'm trying to test.
assert.Error(t, err)

// Reading this line of code someone could (completely reasonably) assume
// that the error has the expected error message. Of course that's not at all
// the case. The expectedErr is just ending up as msgAndArgs...
assert.Error(t, err, expectedErr)
```

Even with typed errors, the contents of the error message is often relevant, as it will be printed to the user somehow (stdout, log file, http response, etc).  

I disagree that checking the error message in a test does anything to encourage error handling using string comparison. It's simply a convenient way of testing that a function behaves properly. There are plenty of applications where a typed error is unnecessary because there is no need to recover from the error, and the message is all that is relevant.

That said, do you have any suggestions on an assertion that would actually encourage the use of typed errors?

```go
assert.ErrorType(t, err, CustomErrorType(nil))
```

?

**Comment by dnephin** [comment] 2017-12-31 02:35
Another thing to consider is that https://godoc.org/github.com/pkg/errors is one of the best ways to handle errors. Wrapping an instance of an error, and using if/switch with `errors.Cause(err)` to look through the wrapping for the root cause. With that package an assertion might look like:

```go
assert.Equal(t, errors.Cause(err), ErrNotFound)
```

But if the unit under test is a higher level abstraction, that itself just wraps an already wrapped error, then checking for the concrete type might not be what you want. In that case using `ErrorContains()` to check for just the wrapped message would be the most correct way of handling it. This is often where I would use this assertion.

**Comment by ernesto-jimenez** [comment] 2017-12-31 13:41
@dnephin 

> I would argue that the current assert.Equal() is even worse. It does nothing to encourage types, and can be very misleading:

I agree. I wish removing `msgAndArgs` from all assertions was a backwards-compatible change.

If we were to do testify v2.0.0, we would definitely remove it.

Really looking forward to `dep` picking up traction in order to be able to do a new major version.

> Even with typed errors, the contents of the error message is often relevant, as it will be printed to the user somehow (stdout, log file, http response, etc).

Sure, but error messages are not part of the package's API and are subject to change.

In these cases I would usually:
* unit-test the `Error()` method on the custom error
* in other tests, check the type or behaviour of the error

```go
// type check
assert.Error(t, err)
assert.IsType(t, err, *CustomError(nil))

// behaviour check
assert.Error(t, err)
if e, ok := err.(interface {
    Temporary() bool
}); ok {
    assert.Truef(t, e.Temporary(), "error should be temporary. was: %s", err)
} else {
    assert.Failf(t, "%T should implement interface { Temporary() bool }", err)
}
```

> That said, do you have any suggestions on an assertion that would actually encourage the use of typed errors?

`assert.ErrorType` would be good.

One question: would you expect this to pass?

```go
// err is of type net.UnknownNetworkError
assert.ErrorType(t, err, net.Error(nil))
```

> But if the unit under test is a higher level abstraction, that itself just wraps an already wrapped error, then checking for the concrete type might not be what you want. In that case using ErrorContains() to check for just the wrapped message would be the most correct way of handling it. This is often where I would use this assertion.

If your package is wrapping an errors and introducing a higher level of abstraction to add more metadata, wouldn't you have an API to allow consumers to get to the wrapped error with the extra metadata?

Something along these lines:

```go
func IsCustomError(err error) (*CustomError, bool) {
	type causer interface {
		Cause() error
	}

	for err != nil {
		if err, ok := err.(*CustomError); ok {
			return err, true
		}
		cause, ok := err.(causer)
		if !ok {
			break
		}
		err = cause.Cause()
	}
	return nil, false
}
```

It is more aligned with how the `os` package handles checks for errors that depend on the system. e.g: `os.IsExist(err)` and `os.IsPermission(err)`.

**Comment by dnephin** [comment] 2017-12-31 22:12
> One question: would you expect this to pass?

Yes, I would expect that `ErrorType()` should only accept interface types as the "type" and use `reflect.Type.Implements()` to check the condition. I guess this is already implemented as https://godoc.org/github.com/stretchr/testify/assert#Implements (except the args are in the opposite order, which is a separate issue).

> If your package is wrapping an errors and introducing a higher level of abstraction to add more metadata, wouldn't you have an API to allow consumers to get to the wrapped error with the extra metadata?
> Something along these lines:

Those lines are almost exactly what `errors.Cause()` already does: https://github.com/pkg/errors/blob/master/errors.go#L256

But no, I would not expect yet another error type. `errors.Wrap()` would wrap an instance of an error, and the instance is what lets you determine the classification of the error. Many times the "extra metadata" is just contextual information for a human to help debugging.

This is related to:

> in other tests, check the type or behaviour of the error

It does not make sense to create a unique error type for every single error in an application. Types are a good way to classify an error, but creating a separate type for every error would make the code harder to understand and harder to consume. Checking the type of the error is not sufficient in some cases.

A function might return the same error type with a different message for difference error cases. Callers of the function may not need to know the difference between those cases, but to fully test the behaviour you need to be able to differentiate the two cases, which would be done with `ErrorContains()`.

With `pkg/errors` you don't really need to create types/interfaces. You define the classes of errors as instances of an `error` using `var ErrX = errors.New(...)`,  you return errors using `errors.Wrapf(ErrX, "extra context"), then any code which needs to know the error type uses `errors.Cause()` see https://godoc.org/github.com/pkg/errors#hdr-Retrieving_the_cause_of_an_error

> Sure, but error messages are not part of the package's API and are subject to change.

Sure, lots of things are subject to change. That is not a good reason to avoid testing it.

**Comment by torkelrogstad** [comment] 2019-10-29 14:34
With the new error wrapping functionality in Go 1.13 it would be nice to have `assert.Wraps(*testing.T, error, error)`, or something similar. Is this something you have considered?

**Comment by eberkund** [comment] 2020-01-17 07:08
@ernesto-jimenez would you consider changing your mind post-1.13? 

https://blog.golang.org/go1.13-errors

**Comment by alxn** [comment] 2021-08-10 00:17
oh, this is fixed in #1022

**Comment by tisonkun** [comment] 2021-09-21 12:03
@alxn @boyan-soubachov my scenario is a bit different and more like "ErrorRegexp"

```go
require.Error(t, err)
require.Regexp(t, ".*context canceled.*" /* rx */, err.Error())
```

Do you think it worth a matcher or before we expose ErrorContains, extend it?

**Comment by tylerauerbeck** [comment] 2021-12-06 07:46
It looks like https://github.com/stretchr/testify/pull/1022 was merged almost a year ago. Are there any plans for a new release to be cut so that this can be referenced with a tagged release?

**Comment by webmaster128** [comment] 2022-05-03 15:41
Seems like this feature is included in 1.7.1.

**Comment by alxn** [comment] 2022-05-03 22:23
vote to close this issue?

**Comment by boyan-soubachov** [comment] 2022-05-03 22:30
Marking as closed

**Closed by boyan-soubachov** 2022-05-03 22:30 UTC
