### ISSUE TITLE
assert dont fail when nil is expected

### ISSUE THREAD

**Issue by Tommy-42** [stretchr/testify#599] opened 2018-05-09 12:05 UTC
Hey there,

I've a strange behavior, I might miss something or do something wrong.

I am currently using testify/assert and testify/suite

with : 

```go
type MyTestSuite struct {
	suite.Suite
    // some custom field
    db
}

func TestMyTestSuite(t *testing.T) {
     // init db
     // blabla

    suite.Run(t, &MyTestSuite{
        db
    })
}

func (s *MyTestSuite) TearDownTest() {
	s.db.Query(nil, "DELETE FROM table;")
}

func (s *MyTestSuite) TestMyFunc() {

    foo, err := MyFunc(bar)

    assert.NotNil(s.T(), err) // err is nil here but dont fail
    assert.Nil(s.T(), foo)
    assert.Equal(s.T(), err.Error(), "failed")  // thus SIGSEGV happend here

   // followed by a lot of test after and more assert
}
```

The problem is that I have a SIGSEGV on 
`assert.Equal(s.T(), err.Error(), "failed")` 

because `err` is nil but it should not happen since I check `assert.NotNil(s.T(), err)` right before.

I dont know why it pass, did I miss something somewhere ?

Thanks for your time,
Tommy

**Comment by Tommy-42** [comment] 2018-05-09 15:19
I've tested with `assert.Error()` / `assert.NoError()` since it looks like more appropriate for asserting error , but I go the same behavior.

**Comment by devdinu** [comment] 2018-05-12 03:01
Can you share code to reproduce this, `MyFunc(bar)` is abstracted and if its not nil `err.Error()` shouldn't fail, There could be more variable here. A simple function returns the error, and the unexpected behaviour (whole output).

**Comment by devdinu** [comment] 2018-05-24 05:56
You should return `error ` from foo function and it should work.

```
func foo() *MyError {
   return nil;
}
```

Be careful about returning nil pointer to the error, `var e *MyError` though e is nil it would fail `NoError`, and printing it would return the value returned from `func Error()`.

**Comment by rvdwijngaard** [comment] 2018-05-24 07:34
@devdinu thanks for your comment; I changed the code and it works. Do you have an explanation for this issue? 
```
fmt.Println(err == nil) // this prints true 
```

**Comment by devdinu** [comment] 2018-05-29 04:34
@rvdwijngaard https://groups.google.com/forum/#!topic/golang-nuts/wcrZ3P1zeAk

**Comment by samkreter** [comment] 2018-06-27 23:22
+1 on this issue. Also have cases where assert.Equal doesn't fail when two integers are not equal.

**Comment by devdinu** [comment] 2018-06-28 04:12
@samkreter Could you share the code, for us to help. Did you have `defer` function `recover()` which recovered the error.

Equal with integers would be straightforward, and should pass, guessing the integer would be a return value from a `func`, which wouldn't have met your expectation.

**Comment by samkreter** [comment] 2018-06-28 16:23
@devdinu It was a misunderstanding on my part. I was expecting the fatal error like in the require package.

**Comment by prologic** [comment] 2019-04-17 01:31
I also experience this as well from time to time.

Example:

```
=== RUN   TestAgent//v1/agent/health
res: (*nomad.AgentHealthResponse)(nil)err: &url.Error{Op:"Get", URL:"http://127.0.0.1:4646/v1/agent/health", Err:(*net.OpError)(0xc00018a0a0)}panic: runtime err
```

Is the issue at hand here some libraries returning a pointer to an error?

**Comment by prologic** [comment] 2019-04-17 01:33
In my case the `&url.Erorr` is coming form the `net/http.Client{}` And the documentation says:

> Any returned error will be of type *url.Error. The url.Error value's Timeout method will report true if request timed out or was canceled.

**Comment by prologic** [comment] 2019-04-17 01:45
https://github.com/stretchr/testify/issues/311 looks related here but its unclear to me why I still run into this :/

**Comment by prologic** [comment] 2019-04-17 02:00
This is really weird; I can't seem to reproduce this in any way that I *think* is what's going on here;

Take for example:

`foo_test.go`:

```#!go
package main_test

import (
	"errors"
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Foo() error {
	return errors.New("kaboom")
}

func Bar() error {
	_, err := http.Get("http://127.0.0.0:0")
	if err != nil {
		return err
	}
	return nil
}

func TestFoo(t *testing.T) {
	assert := assert.New(t)

	err := Foo()
	assert.NoError(err)
}

func TestBar(t *testing.T) {
	assert := assert.New(t)

	err := Bar()
	assert.NoError(err)
}
```

And `$ go test -v .`:

```#!sh
$ go test -v .
=== RUN   TestFoo
--- FAIL: TestFoo (0.00s)
    foo_test.go:27:
        	Error Trace:	foo_test.go:27
        	Error:      	Received unexpected error:
        	            	kaboom
        	Test:       	TestFoo
=== RUN   TestBar
--- FAIL: TestBar (0.00s)
    foo_test.go:34:
        	Error Trace:	foo_test.go:34
        	Error:      	Received unexpected error:
        	            	Get http://127.0.0.0:0: dial tcp 127.0.0.0:0: connect: can't assign requested address
        	Test:       	TestBar
FAIL
FAIL	assert_noerror	0.016s
```

This *works* as expected. Mystery continues...

**Comment by weijinw** [comment] 2019-05-01 17:45
Got the same behaviors, any workaround or fix for this.

**Comment by trungtvq** [comment] 2019-06-17 09:22
![image](https://user-images.githubusercontent.com/40919061/59593334-f0b44000-911b-11e9-8b45-f0b8ab7c85b9.png)
you have to add this line for multi assert:
  assert := assert.New(t)

**Comment by serbrech** [comment] 2019-07-19 15:07
`assert := require.New(t)`

there... you'll get the *expected* behavior ;)

**Comment by ghostsquad** [comment] 2019-07-20 02:53
to be clear, the expected behavior is that the test immediately stops if the assert fails?

**Comment by serbrech** [comment] 2019-07-20 08:02
@ghostsquad
That’s what this thread is about, people who got confused why their tests did not fail. I think that’s because in most other languages, assert libraries will fail the test right away, because you don’t write tests with loops.

**Comment by ghostsquad** [comment] 2019-07-20 16:40
I like the ability to see multiple failures at once, but it can be a little confusing. I think the README should just be updated to make this very clear, and provide a description of how to get this desired behavior.

**Comment by creasty** [comment] 2019-07-21 07:52
Well, this is obviously a bad design.

> I think that’s because in most other languages, assert libraries will fail the test right away, because you don’t write tests with loops.

Not only for this reason, but also for the fact that `NotNil` being the only function that behaves differently and inconsistently from the other functions.

Here's my suggestions:

1. Keep the behavior and rename the function for the sake of clarity. (e.g., `WarnIfNil`)
2. Implement the `NotNil` in the way most people expect.
3. Change the behavior of `NotNil` and create a new function that has the original behavior. (Combination of 1&2)
4. Completely get rid of `NotNil` from the API as it's confusing.

**Comment by ghostsquad** [comment] 2019-07-21 08:31
@serbrech @creasty is it true that this is the only function that doesn't immediately fail the test? I thought it was all functions.

Assuming that I'm correct, in that _all functions_ operate this way, there should probably be a second set of functions that immediately fail the test when the assertion is not met.

I think using "Must" is probably the right lingo.

```
assert.MustBeNil
assert.MustNotBeNil
```

This maintains backward compatibility and can be _easily_ explained in the readme like this:

---

Functions ending in `Must` will halt further execution of a test case if the assertion is not met. This is the typical behavior from other assertion libraries in other languages.

```go
assert.MustNotBeNil(t, foo)

# if foo is nil, this assert will not be evaluated
assert.MustEqual(t, bar, foo)
```

Other functions will not halt the execution of the test. You can use them in conditional statements to avoid panics and superfluous assertion output.

This allows you to see failures of multiple asserts in your test, and fix them at the same time without needing to run the tests multiple times.

```go
if assert.NotNil(t, foo) && assert.Len(t, foo, 1) {
  assert.Equal(t, "first", foo[0])
}

assert.Equal(t, "somthing", baz)
```

**Comment by serbrech** [comment] 2019-07-21 09:27
@ghostsquad That’s what the require package is for.

**Comment by Blquinn** [comment] 2019-10-09 17:14
For anyone who is interested (@Tommy-42 ), you can make your own custom suite.Suite struct, which will default to using require.Assertions, instead of the assert.Assertions by doing the following.

```go
// Suite is copied directly from testify/suite, the only difference being
// that it nests require.Assertions, instead of the assert.Assertions.
// This changes the default behavior of suite.Equal() et al. to fail on
// the first test that fails.
//
// Regular assertions can be accessed via suite.Assert().
//
// All other behavior of the suite should be exactly the same as the
// testify suite.
type Suite struct {
	*require.Assertions
	assert *assert.Assertions
	t      *testing.T
}

func (s *Suite) T() *testing.T {
	return s.t
}

// SetT sets the current *testing.T context.
func (s *Suite) SetT(t *testing.T) {
	s.t = t
	s.assert = assert.New(t)
	s.Assertions = require.New(t)
}

func (s *Suite) Assert() *assert.Assertions {
	if s.assert == nil {
		s.assert = assert.New(s.T())
	}
	return s.assert
}

func (s *Suite) Require() *require.Assertions {
	if s.Assertions == nil {
		s.Assertions = require.New(s.T())
	}
	return s.Assertions
}
```

Use this as you would the normal suite.Suite.

@devdinu Pretty sure this ticket can be closed based on @serbrech 's comment.

**Comment by mvdkleijn** [comment] 2020-07-30 18:57
Closing this but we'll discuss this topic more in #829

**Closed** 2020-07-30 18:57 UTC
