### ISSUE TITLE
package pointer type variable definitions becomes nil in the middle of test cases

### ISSUE THREAD

**Issue by aacanakin** [stretchr/testify#278] opened 2016-02-22 09:38 UTC
Here's my example;
```go
var engine *Engine

func TestSetup(t *testing.T) {
    engine = NewEngine(someParams)
}

func TestUseEngine(t *testing.T) {
    fmt.Println(engine) // prints nil
}
```

The engine struct and `NewEngine()` is the following;
```go
type Engine struct {
	driver string
	dsn    string
	db     *sql.DB
}

// NewEngine generates a new engine and returns it as an engine pointer
func NewEngine(driver string, dsn string) (*Engine, error) {

	conn, err := sql.Open(driver, dsn)
	if err != nil {
		return nil, err
	}

	return &Engine{
		driver: driver,
		dsn:    dsn,
		db:     conn,
	}, err
}
```
I guess this bug started after 1.6 release. It seems to be a garbage collection bug. Any ideas to fix that?

**Comment by ernesto-jimenez** [comment] 2016-02-22 09:42
@aacanakin, can you share a small `example_test.go` file that reproduces the error?

Something we can run too and see it failing in order to debug the issue.

Thanks!
Ernesto

**Comment by aacanakin** [comment] 2016-03-01 19:41
I'll open source a repo probably in a week. I'll post the link.

**Comment by ernesto-jimenez** [comment] 2016-03-01 19:58
@aacanakin sharing a small code sample reproducing the bug will be better than a full repo, so the sample can discard the issue being with your project and confirm it's a testify issue :)

**Comment by aacanakin** [comment] 2016-03-01 20:41
@ernesto-jimenez ok then. Here's a relatively small example;
```go
package qb

import (
	"database/sql"
	_ "github.com/mattn/go-sqlite3"
	"github.com/stretchr/testify/assert"
	"testing"
)

type Engine struct {
	driver string
	dsn    string
	db     *sql.DB
}

// NewEngine generates a new engine and returns it as an engine pointer
func NewEngine(driver string, dsn string) (*Engine, error) {

	conn, err := sql.Open(driver, dsn)
	if err != nil {
		return nil, err
	}

	return &Engine{
		driver: driver,
		dsn:    dsn,
		db:     conn,
	}, err
}

var sEngine *Engine

func TestSqliteSetup(t *testing.T) {
	sEngine, err := NewEngine("sqlite3", ":memory:")
	assert.Nil(t, err)
	assert.NotNil(t, sEngine)
}

func TestExec(t *testing.T) {
	assert.NotNil(t, sEngine)
	t.Log(sEngine)
}
```
When I run this;
```
$ go test -v sqlite_test.go
=== RUN   TestSqliteSetup
--- PASS: TestSqliteSetup (0.00s)
=== RUN   TestExec
--- FAIL: TestExec (0.00s)
        Error Trace:    sqlite_test.go:40
	Error:		Expected value not to be nil.

	sqlite_test.go:41: <nil>
FAIL
exit status 1
FAIL	command-line-arguments	0.018s
```

**Comment by ernesto-jimenez** [comment] 2016-03-01 20:48
@aacanakin if you want to do some setup before your tests, you should use either [`TestMain`](https://godoc.org/testing#hdr-Main) if you want to do a setup for all your tests in a global variable or [`testify/suite`](https://godoc.org/github.com/stretchr/testify/suite).

That example was relying on tests' side-effects (one test running earlier and setting up certain global variable), and you should never rely on such side-effects :)

**Comment by ernesto-jimenez** [comment] 2016-03-01 20:49
I'm closing the issue since testify is working correctly here :)

**Closed by ernesto-jimenez** 2016-03-01 20:49 UTC
