### ISSUE TITLE
Panic in diffArguments if len(expected) > len(actual)

### ISSUE THREAD

**Issue by improbable-bradley** [stretchr/testify#424] opened 2017-04-05 13:09 UTC
If you have a mocked method and call it with fewer arguments than expected then mock.go:719 panics with an index out of range error.

If the actual arguments length is shorter than expected then when showing the diff it should be padded with blank arguments in order to display properly. There should also be a warning that the argument lengths are mismatched.

**Comment by nathanboktae** [comment] 2017-05-05 17:56
Dupe of #393, and #417 is the little PR that fixes it. I ran into this too.

**Closed** 2017-05-28 14:34 UTC
