### ISSUE TITLE
Change order of signature in `Exactly`, `Equal`, ...etc.

### ISSUE THREAD

**Issue by jaychsu** [stretchr/testify#1043] opened 2021-01-27 02:16 UTC
code: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L479

requested change: to swap the order of input params `expected`, `actual` in apis `Exactly`, `Equal`, ... etc.

before change: 

```
func Exactly(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool {
...
```

after change: 

```
func Exactly(t TestingT, actual, expected interface{}, msgAndArgs ...interface{}) bool {
...
```

reason: 

to unify the calling behavior with another api, e.g., 

when we call `Subset`, `Len`. the calling likes `suite.Subset(ActualSet, ExpectSubSet)`, `suite.Len(ActualList, ExpectedLen)`

but when we call `Exactly`, we should pass param by different order `suite.Exactly(ExpectedObj, ActualObj)`

**Comment by kyoh86** [comment] 2021-01-31 06:02
+1
I know that it is a destructive change. But I really want it too.

**Comment by SaeeSaadat** [comment] 2021-02-02 00:07
i just changed the order of Len and Lenf in another pull request. most functions are using (expected, actual) order

**Comment by brackendawson** [comment] 2021-05-12 18:58
I think this is a duplicate of #146 which is already in the v2.0.0 milestone.

**Closed** 2024-02-01 00:46 UTC
